[package]
name = "miratope"
version = "0.1.0"
authors = ["Violeta Hernández <vi.hdz.p@gmail.com>", "Grayson Burton <ocornoc@protonmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.4.0"
scapegoat = "1.0.0"
gcd = "2.0.1"
nalgebra = {version = "0.25.1", features = ["serde-serialize"]}
petgraph = "0.5.1"
rand = "0.8.3"
ron = "0.6.4"
serde = {version = "1.0.123", features = ["derive"]}
bevy_egui = "0.3.0"

[profile.release]
lto = "thin"
incremental = true
